language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - nightly
    - hhvm
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-dist --optimize-autoloader"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - composer config --list --global

script:
  - ./bin/phpunit
